{% set name = "sphinxcontrib-paverutils" %}
{% set version = "1.17.0" %}
{% set sha256 = "daafc4440018c34b0ab3fe55b72e6c1c484a23622fb3caf73f08f77fb458c149" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - sphinx >=0.6
    - paver >=1.02.0

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.paverutils

about:
  home: https://bitbucket.org/dhellmann/sphinxcontrib-paverutils/
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Sphinx/Paver integration'

extra:
  recipe-maintainers:
    - johannesring
    - kghustad
