{% set name = "sphinxcontrib-paverutils" %}
{% set version = "1.16.0" %}
{% set sha256 = "124a4e030d4975c0d0d778be7ae1bfda828d896f04272436fe323cd2e8c3bcf5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - sphinx >=0.6
    - paver >=1.02.0

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.paverutils

about:
  home: https://bitbucket.org/dhellmann/sphinxcontrib-paverutils/
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Sphinx/Paver integration'

extra:
  recipe-maintainers:
    - johannesring
    - kghustad
