{% set name = "sphinxcontrib-paverutils" %}
{% set version = "1.18.1" %}
{% set sha256 = "8abaed9b77cf1e477c647193d2eb876947dc8313ee2b6439d6fc0ffcb0552953" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr

  run:
    - python
    - sphinx >=0.6
    - paver >=1.02.0

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.paverutils

about:
  home: https://bitbucket.org/dhellmann/sphinxcontrib-paverutils/
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Sphinx/Paver integration'

extra:
  recipe-maintainers:
    - johannesring
    - kghustad
