# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZL9Vcvh9iNa7KVXAuWwLWOykm35n2tiF84GGbDSsVPyXmsAuailfGG5e+nf7WZ/8WFiKSsKBvgDlYigKIAzVdXWpmXLL1g5kvUH88qv77OLrbKT33IR6dWe/6sVM/sACs83s9wDBjW6cNRgg+NM7Y/VoHD5Jsig6NNlxYS1JNUE6EfUFMzQcbXum3sbSLZskLtRhxRUhPzD/FYaQbmA6003FhjE+5APk98jqKtaGMEWzhvAidJanOHnWeDRwew39007WGlJiybT857ZcXXiM3tZHH/gh88UDmGboptN0XlWKUgQ+xUwNqSoHQAZ/rQTin1dOWhPRVOKXtZb+QtlXyfgjCWRNGxiVXZ4c+TrbS6XeIoSb1QP+nK5iUdkFY4i0Jw2p+QycsbflyiN3rJ2zvaEdhgfjEKVVXB6ORyIAWeEPAcOl4yP/mHj3o3WBicer7stObjjgHm0raZ5TUvOTi0A20RIrJKaqPIA4fPDsta3XZFYB7VqPyCwWmbc7gFfMH8a5UvvvXYjLy3kIYwO61Pn2eq0mjjUC8dZWDPMxq+1CJpi3732frqv71q8qCNZ6n4AEwtS1YXT6cRlsOlD/hta1hCB7rlMpOU3VV7UrpeXJYVOcUZwfVeSpaBg48q8ER+Q/wo4OmYqhfGD91OETKenM3vrRxE1olxeD07C8Xvk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
