travis:
  secure:
    BINSTAR_TOKEN: K/HlGLFh1vD2JHKb6JSmS5d0MtafaWs76pkvOUWkHmhFzrOzjZGoFg9wOeWdkCxDjvMYF7jwyXFYG4tDmp0JjOZcGNXSYJfr2V85a4Nzun6W64M/2j8N2Bl7r8anFk0gYp6fTI5Otrb0nrGdZmXfEQ9Gc1GiTo7iuF29byI1GPfGEpAN0oMGMsi4aJ202WiGPpKSclhVtu/P2XpLHav8+NhSQ+yM4RIWVOfI6s8uBxyQkucRfWAP+sMsKLSk3peeICIaOKjxoQpbgAiwzhcPhCbcgYQz5iTXr0Lqvv6/Fz9QINDSg5+FQaPrbrcMUfwldQzGoiPJtwhcpO5ZIyli+SLgJpTNr+OW6Y3TJYPxpJH/XoKUlYsvOWFNDcUTfTTGOJ1Tyevbt7s7QXsUICG/UHGMJu6K+1MLNIMwlLKdi56UL17Ok30ipNOpX7RqYwds8QpF9QJFGIErgxvBWPjAPXIs15xVWGsVqnQtf4RvpGFX9LcQtjHW29BD72pU4wxl5u2TpDz5YyzCl98DTJ8Uv4TpIW5WvL33vSJVIS7glNNxRppXnZSUGbuj9Yyd//huJhOa0C7Mxfzkvy61lTBG7LgP70wrLdNSPt0hMgb6fLB/VnncSrSIFej+rz/8uV840BIBRSuRwkqtHjK2rYoyEz2yzGi2PzViVAGQmO5X7ys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
