travis:
  secure:
    BINSTAR_TOKEN: bG+C8Gkm2UEiwd3/8BDsckS/VVfi8n3dUcHGhWxg71T0BJKcS0j73PPkbSqz/YLkAJJT120hduirwv1L2k5+/fWf5kIcwLUl5NUt2JvrLadcuvOwYwIf9g4OZ3eBeUmgRyfirp5t5g4NdwxpOfzlkO4L6bURnfzI07EaiFDDepODxwxKujI80G0iKwdlIS9/jhkAysCsFjq/pCCf4ggbCKA9IS6ByTxmWhQL3iV8udO2ftNqOSJ3WMlgDFESrHVzEjnBfgwXNONBvqMdvziaBR93zNaUjHPJ2jHLEKPbUjFl7WF9qXGIW1qYQ/GclxwDCnfV9Ik+UjVvwKGqdsO35c934Be8zIsTFHiHH5NVtTVz3YNNc6BF1Qo3Yk23cdcOAOYyT8gsmTJ2JVgYHRNuZAC38io6w5XYfXkUcdZn4oJItzd9Ive3z73rj6hEExLCSd67WGWqQreZQXO8qxMZJKTFAh68LPb28AyuHFGG30rQUyPsD/RZI1ZhsyQQGwgq2E/1woM7JIU7vZVNWNDufQAAUxXdBErGOKuW7uTOsvcytfQBjFPQzjid29AUNhD6FOLXVCyiMnBJJOFFSuDmnUf6d8bP5fGz+Yuh23pewWbVgj8ybv7f3+Z08q/6hZFODkXZ5fYxJvAeSD0ft7L1863Gaax343HBLJshalj2lwA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
